apiVersion: v1
kind: Service
metadata:
  name: result-serviec
  labels:
    name: result-service
    app: demo-voting-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      tartgetport: 80
  selector:
    ame: result-app-pod
    app: demo-voting-app