apiVersion: v1
kind: Service
metadata:
  name: voting-serviec
  labels:
    name: voting-service
    app: demo-voting-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      tartgetport: 80
  selector:
    name: vote-app-pod
    app: demo-voting-app